FROM node:20.12.0-alpine3.19

WORKDIR /bankWebhook/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Can you filter the build down to just one app?
RUN npm run bank-webhook-build

EXPOSE 3002

CMD ["npm", "run", "start-web-hook"]